// <auto-generated />
using System;
using ArbitrageDomain.DbLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbLayer.Migrations
{
    [DbContext(typeof(SpreadDbContext))]
    [Migration("20250406191121_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArbitrageDomain.Model.PairSpread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FirstFutures")
                        .HasColumnType("integer");

                    b.Property<decimal>("FirstFuturesPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("SecondFutures")
                        .HasColumnType("integer");

                    b.Property<decimal>("SecondFuturesPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Date", "FirstFutures", "SecondFutures")
                        .IsUnique();

                    b.ToTable("PairSpreads");
                });
#pragma warning restore 612, 618
        }
    }
}
